### ISSUE TITLE
TIFF, BMP and GIF support

### ISSUE THREAD

**Issue by tracker1** [lob/calipers#26]
I know that these are less common for most use cases, but being able to determine a couple more formats for images would be useful.

**Comment by mgartner** [comment]
Thanks for the feedback!

FYI, Support for GIFs was added in v1.2.0. https://github.com/lob/calipers/blob/master/CHANGELOG.md

I'll look into adding TIFF and BMP support.

**Comment by Pana** [comment]
+1

**Comment by tracker1** [comment]
@mgartner, I've seen several PRs related to BMP, and iirc TIFF, is this still an open/incomlete issue?

**Comment by mgartner** [comment]
Hi @tracker1, I just released v1.5.0 which adds support for BMP. The only remaining format not supported is TIFF. I've created a new issue to track that.
